// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQJn8HzpB2mtuRwt44PD289Omgk5EX38U',
    appId: '1:205104965948:web:dbe7cf0121d1afcf7b9639',
    messagingSenderId: '205104965948',
    projectId: 'formconnectfirebase-d1c0d',
    authDomain: 'formconnectfirebase-d1c0d.firebaseapp.com',
    databaseURL: 'https://formconnectfirebase-d1c0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'formconnectfirebase-d1c0d.firebasestorage.app',
    measurementId: 'G-NDCYJQE6KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTSKh1qJnJGVmmWQsfuM28GBPoyADYm8I',
    appId: '1:205104965948:android:04c94ec597cd520a7b9639',
    messagingSenderId: '205104965948',
    projectId: 'formconnectfirebase-d1c0d',
    databaseURL: 'https://formconnectfirebase-d1c0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'formconnectfirebase-d1c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczL4UxCNx3GMnfqY1Zi1JYrzXWlfuQRM',
    appId: '1:205104965948:ios:b47185b5112918137b9639',
    messagingSenderId: '205104965948',
    projectId: 'formconnectfirebase-d1c0d',
    databaseURL: 'https://formconnectfirebase-d1c0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'formconnectfirebase-d1c0d.firebasestorage.app',
    iosBundleId: 'com.example.formconnectfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAczL4UxCNx3GMnfqY1Zi1JYrzXWlfuQRM',
    appId: '1:205104965948:ios:b47185b5112918137b9639',
    messagingSenderId: '205104965948',
    projectId: 'formconnectfirebase-d1c0d',
    databaseURL: 'https://formconnectfirebase-d1c0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'formconnectfirebase-d1c0d.firebasestorage.app',
    iosBundleId: 'com.example.formconnectfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQJn8HzpB2mtuRwt44PD289Omgk5EX38U',
    appId: '1:205104965948:web:3504648945c9c46b7b9639',
    messagingSenderId: '205104965948',
    projectId: 'formconnectfirebase-d1c0d',
    authDomain: 'formconnectfirebase-d1c0d.firebaseapp.com',
    databaseURL: 'https://formconnectfirebase-d1c0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'formconnectfirebase-d1c0d.firebasestorage.app',
    measurementId: 'G-EYYPM0RKFC',
  );
}
